name: personal

on:
  push:
    branches: [ main ]
    paths-ignore: 'README.md'
  workflow_dispatch:

jobs:
  ssh:
    runs-on: ubuntu-20.04

    env:
      # Change These If You Are Forking The Repo
      GitHubName: "tonroses"
      GitHubMail: "rongodie@protonmail.com"

    steps:
    - name: Set Git Configs & Secrets
      run: |
        git config --global user.email ${GitHubMail}
        git config --global user.name ${GitHubName}
        git config --global color.ui true
        git config --global credential.helper store
        echo "https://${GitHubName}:${{ secrets.GITHUB_TOKEN }}@github.com" > ~/.git-credentials
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${GitHubName} --password-stdin
        git clone https://${GitHubName}:${{ secrets.PW }}/tonroses/memebot /home/runner/memebot
        cd /home/runner/memebot
        docker build . --rm --force-rm --compress --no-cache=true --pull --file Dockerfile -t mirror-bot
        docker image ls
    - name: running Docker
      timeout-minutes: 340
      continue-on-error: true
      run: |
        docker run --privileged --rm -i mirror-bot
    - name: Self Looping
      run: |
        curl -X POST --header "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${GITHUB_REPOSITORY}/actions/workflows/personal.yml/dispatches -d '{"ref":"main"}'
